### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by davidagold** [davidagold/StructuredQueries.jl#19]
~~The title says it all. If there anything folks feel strongly about adding, please do chime in.~~

~~Required:~~

This issue is now about setting milestones for a number of projects. Feedback and suggestions welcome. The following is not exhaustive.

0.0.1
- [x] name the darn thing #8
- [x] show methods for `Query`s and graphs #15 

0.0.2
- [x] `filter` processing brought to current state (aggregating all conditions before generating a kernel-defining expression).

0.0.3
- [x] test coverage > 80%
- [x] documentation of user-facing interface

0.0.4
- [ ] test coverage > 90%
- [x] documentation of internals

0.1.0
- [ ] SQLQuery interfacing https://github.com/yeesian/SQLQuery.jl/pull/2
- [ ] using a `Query` object as a data source within an invocation of `@query` should extend the original `Query` object #20
- [ ] finalize syntax
- [ ] parametrized queries API.

**Comment by davidagold** [comment]
So, I'm punting these to 0.0.2, . Some of these are actually fairly large design decisions, some of them are just more work than I'm able to put in at the moment. But none of them should delay tagging a 0.0.1 version of this package.
